job/urls.py
from django.contrib import admin
from django.urls import path , include
from account.views import activate
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
    path('', include('account.urls')),
    path('', include('letter.urls')),
    path('', include('posts.urls')),
    path('cv/', include("cvbuilder.urls")),
    path("quiz/", include("quiz.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    
    
    
    path('activate/<uidb64>/<token>',
        activate, name='activate'),

    path('oauth/', include('social_django.urls', namespace='social')),


   path('password_reset_form/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset_form.html'
         ),
         name='password_reset'),
         
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapp/urls.py
from django.urls import path
from jobapp import views
from django.conf import settings
from django.conf.urls.static import static

from .import views
app_name = "jobapp"


urlpatterns = [

    path('', views.home_view, name='home'),
    path('jobs/', views.job_list_View, name='job-list'),
    path('job/create/', views.create_job_View, name='create-job'),
    path('job/<int:id>/', views.single_job_view, name='single-job'),
    path('apply-job/<int:id>/', views.apply_job_view, name='apply-job'),
    path('bookmark-job/<int:id>/', views.job_bookmark_view, name='bookmark-job'),

    path('about/', views.AboutUsView, name='about'),
    path('FAQ/', views.FAQ, name='FAQ'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    

    path('contact', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    
    path('result/', views.search_result_view, name='search_result'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    
    path('dashboard/employer/job/<int:id>/applicants/', views.all_applicants_view, name='applicants'),
    path('dashboard/employer/job/edit/<int:id>', views.job_edit_view, name='edit-job'),
    path('dashboard/employer/applicant/<int:id>/', views.applicant_details_view, name='applicant-details'),
    path('dashboard/employer/close/<int:id>/', views.make_complete_job_view, name='complete'),
    path('dashboard/employer/delete/<int:id>/', views.delete_job_view, name='delete'),
    path('dashboard/employee/delete-bookmark/<int:id>/', views.delete_bookmark_view, name='delete-bookmark'),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.conf.urls import url
from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake, index, job_category
from django.urls import path



urlpatterns = [ 
    path('', view=index, name='index'),    
    path('quizzes/',view=QuizListView.as_view(),name='quiz_index'),
    path('category/',view=CategoriesListView.as_view(),name='quiz_category_list_all'),
    path('category/(?P<category_name>[\w|\W-]+)/',view=ViewQuizListByCategory.as_view(),name='quiz_category_list_matching'),
    path('progress/',view=QuizUserProgressView.as_view(), name='quiz_progress'),
    path('marking/',view=QuizMarkingList.as_view(),name='quiz_marking'),
    path('marking/(?P<pk>[\d.]+)/',view=QuizMarkingDetail.as_view(),name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
    path('(?P<slug>[\w-]+)/', view=QuizDetailView.as_view(),name='quiz_start_page'),
    path('(?P<quiz_name>[\w-]+)/take/',view=QuizTake.as_view(),name='quiz_question'),
    path("job-cat/<str:category>/", job_category, name="job-category"),

]

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list, widget=RadioSelect)

quiz/views.py
import random

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import FormView
from .forms import QuestionForm
from .models import Quiz, Progress, Sitting, Question
from jobapp.models import Category
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from jobapp.models import Job


class QuizMarkerMixin(object):
    @method_decorator(login_required)
    @method_decorator(permission_required('quiz.view_sittings'))
    def dispatch(self, *args, **kwargs):
        return super(QuizMarkerMixin, self).dispatch(*args, **kwargs)


class SittingFilterTitleMixin(object):
    def get_queryset(self):
        queryset = super(SittingFilterTitleMixin, self).get_queryset()
        quiz_filter = self.request.GET.get('quiz_filter')
        if quiz_filter:
            queryset = queryset.filter(quiz__title__icontains=quiz_filter)

        return queryset


class QuizListView(ListView):
    model = Quiz
    # @login_required
    def get_queryset(self): 
        queryset = super(QuizListView, self).get_queryset()
        return queryset.filter(draft=False)


class QuizDetailView(DetailView):
    model = Quiz
    slug_field = 'url'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class CategoriesListView(ListView):
    model = Category


class ViewQuizListByCategory(ListView):
    model = Quiz
    template_name = 'view_quiz_category.html'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(
            Category,
            category=self.kwargs['category_name']
        )

        return super(ViewQuizListByCategory, self).\
            dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewQuizListByCategory, self)\
            .get_context_data(**kwargs)

        context['category'] = self.category
        return context

    def get_queryset(self):
        queryset = super(ViewQuizListByCategory, self).get_queryset()
        return queryset.filter(category=self.category, draft=False)


class QuizUserProgressView(TemplateView):
    template_name = 'progress.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(QuizUserProgressView, self)\
            .dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuizUserProgressView, self).get_context_data(**kwargs)
        progress, c = Progress.objects.get_or_create(user=self.request.user)
        context['cat_scores'] = progress.list_all_cat_scores
        context['exams'] = progress.show_exams()
        return context


class QuizMarkingList(QuizMarkerMixin, SittingFilterTitleMixin, ListView):
    model = Sitting

    def get_queryset(self):
        queryset = super(QuizMarkingList, self).get_queryset()\
                                               .filter(complete=True)

        user_filter = self.request.GET.get('user_filter')
        if user_filter:
            queryset = queryset.filter(user__username__icontains=user_filter)

        return queryset
    
    class Meta:
        pass


class QuizMarkingDetail(QuizMarkerMixin, DetailView):
    model = Sitting

    def post(self, request, *args, **kwargs):
        sitting = self.get_object()

        q_to_toggle = request.POST.get('qid', None)
        if q_to_toggle:
            q = Question.objects.get_subclass(id=int(q_to_toggle))
            if int(q_to_toggle) in sitting.get_incorrect_questions:
                sitting.remove_incorrect_question(q)
            else:
                sitting.add_incorrect_question(q)

        return self.get(request)

    def get_context_data(self, **kwargs):
        context = super(QuizMarkingDetail, self).get_context_data(**kwargs)
        context['questions'] =\
            context['sitting'].get_questions(with_answers=True)
        return context


class QuizTake(FormView):
    form_class = QuestionForm
    template_name = 'question.html'

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, url=self.kwargs['quiz_name'])
        if self.quiz.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        self.logged_in_user = self.request.user.is_authenticated

        if self.logged_in_user:
            self.sitting = Sitting.objects.user_sitting(request.user,
                                                        self.quiz)
        if self.sitting is False:
            return render(request, 'single_complete.html')

        return super(QuizTake, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=QuestionForm):
        if self.logged_in_user:
            self.question = self.sitting.get_first_question()
            self.progress = self.sitting.progress()
        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizTake, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        if self.logged_in_user:
            self.form_valid_user(form)
            if self.sitting.get_first_question() is False:
                return self.final_result_user()
        self.request.POST = {}

        return super(QuizTake, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizTake, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['quiz'] = self.quiz
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def form_valid_user(self, form):
        progress, c = Progress.objects.get_or_create(user=self.request.user)
        guess = form.cleaned_data['answers']
        is_correct = self.question.check_if_correct(guess)

        if is_correct is True:
            self.sitting.add_to_score(1)
            progress.update_score(self.question, 1, 1)
        else:
            self.sitting.add_incorrect_question(self.question)
            progress.update_score(self.question, 0, 1)

        if self.quiz.answers_at_end is not True:
            self.previous = {'previous_answer': guess,
                             'previous_outcome': is_correct,
                             'previous_question': self.question,
                             'answers': self.question.get_answers(),
                             'question_type': {self.question
                                               .__class__.__name__: True}}
        else:
            self.previous = {}

        self.sitting.add_user_answer(self.question, guess)
        self.sitting.remove_first_question()

    def final_result_user(self):
        results = {
            'quiz': self.quiz,
            'score': self.sitting.get_current_score,
            'max_score': self.sitting.get_max_score,
            'percent': self.sitting.get_percent_correct,
            'sitting': self.sitting,
            'previous': self.previous,
        }

        self.sitting.mark_quiz_complete()

        if self.quiz.answers_at_end:
            results['questions'] =\
                self.sitting.get_questions(with_answers=True)
            results['incorrect_questions'] =\
                self.sitting.get_incorrect_questions

        if self.quiz.exam_paper is False:
            self.sitting.delete()

        return render(self.request, 'result.html', results)


def job_category(request, category):
    print(category)
    # try:
    category = Category.objects.filter(cat_name=category).first()
    job = Job.objects.filter(category=category)
    return render(request, "job-apply.html", {"page_obj":job})

def index(request):
    return render(request, 'index.html', {})

quiz/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">

<head>
  <meta charset="utf-8">

  <title>{% trans "Example Quiz Website" %} | {% block title %}{% endblock %}</title>
  <meta name="description" content="{% block description %}{% endblock %}">

  <!-- styles -->
  <!--<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"
    crossorigin="anonymous">
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Quiz App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav rm-auto">
        {% if user.is_authenticated %}
        <li class="nav-tem" style="color:gray">
          <a href="{% url 'quiz_index' %}" class="nav-link">Quizzes</a>
        </li>
        <li class="nav-tem" style="color:gray">
            <a href="{% url 'quiz_progress' %}" class="nav-link">Progress</a>
          </li>
        {% endif %}

      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item ">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </nav>


  <!-- Before the quiz content -->

  <div class="container">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-warning alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"><sup>&times;</sup></span>
      </button>
      {{message}}
    </div>
    {% endfor %} {% endif %} {% block content %} {% endblock %}

  </div>

  <!-- After the quiz content -->


</body>

</html>

quiz/templates/correct_answer.html
{% load i18n %}
{% if previous.answers %}

{% if user_was_incorrect %}
<div class="alert alert-error">
	<strong>{% trans "You answered the above question incorrectly" %}</strong>
</div>
{% else %}
<div class="alert alert-success">
	<strong>{% trans "You answered the above question correctly" %}</strong>
</div>
{% endif %}
{% endif %}

quiz/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>This is my index page</h1>
{% if user.is_authenticated %}
    <p>Username: {{user.username}}</p>
    <p>Name: {{user.first_name}} {{user.last_name}}</p>
    <p>Email: {{user.email}}</p>
{% endif %}
    
{% endblock  %}

quiz/templates/job-apply.html
   
   <section id="ajax_listing_paginattion" class="site-section services-section bg-light block__62849" id="next-section">
      <div class="container">
    
        <div class="row">
          {% for job in page_obj %}
          <div class="col-6 col-md-6 col-lg-4 mb-4 mb-lg-5">
            <a href="{% url 'jobapp:single-job' job.id %}" class="block__16443 min-h text-center d-block">
              <img class="bord" src="{{ job.image.url }}" alt="..." style="height: 150px;" width="150px">
             
              <h3>{{ job.title }}</h3>
              <ul class="job-listing-meta list-unstyled pl-3 mb-0">
                <li class="menu-fix mb-2">
                  {% if job.job_type == '1' %}
                  <span class="badge badge-primary">
                    Full Time
                  </span>
                  {% elif job.job_type == '2'%}
                  <span class="badge badge-danger">
                    Part Time
                  </span>
                  {% else  %}
                  <span class="badge badge-info">
                    Internship
                  </span>
                  {% endif %}</li>
                <li class="badge badge-secondary menu-fix mb-2"> {{ job.location }}</li>
              </ul>
              <p>{{  safe | truncatechars:150}}</p>
            </a>
          </div>
          {% endfor %}
        </div>
        {% include 'jobapp/paginator.html' %}
    
      </div>
    </section>

quiz/templates/login.html
{% extends "base.html" %} {% block content %}

<div class="col-md-6 offset-md-3">
    <h1 class="text-center">Login</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Enter Registeration Id" name="username">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder=" Enter Password" name="password">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>

{% endblock %}

quiz/templates/progress.html
{% extends "base.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {% trans "Progress Page" %} {% endblock %}
{% block description %} {% trans "User Progress Page" %} {% endblock %}

{% block content %}

  {% if cat_scores %}

  <h1>{% trans "Question Category Scores" %}</h1>

  <table class="table table-bordered table-striped">

	<thead>
	  <tr>
		<th>{% trans "Category" %}</th>
		<th>{% trans "Correctly answererd" %}</th>
		<th>{% trans "Incorrect" %}</th>
		<th>%</th>
	  </tr>
	</thead>

	<tbody>


	  {% for cat, value in cat_scores.items %}
	  <tr>
		<td>{{ cat }}</td>
		<td>{{ value.0 }}</td>
		<td>{{ value.1 }}</td>
		<td>{{ value.2 }}</td>
	  </tr>

	  {% endfor %}

	</tbody>

  </table>


  {% endif %}

  {% if exams %}

  <hr>

  <h1>{% trans "Previous exam papers" %}</h1>
  <p class="lead">
	{% trans "Below are the results of exams that you have sat." %}
  </p>

  <table class="table table-bordered table-striped">

	<thead>
	  <tr>
		<th>{% trans "Quiz Title" %}</th>
		<th>{% trans "Score" %}</th>
		<th>{% trans "Possible Score" %}</th>
		<th>%</th>
	  </tr>
	</thead>

	<tbody>

	  {% for exam in exams %}

	  <tr>
		<td>{{ exam.quiz.title }}</td>
		<td>{{ exam.current_score }}</td>
		<td>{{ exam.get_max_score }}</td>
		<td>{{ exam.get_percent_correct }}</td>
	  </tr>

	  {% endfor %}

	</tbody>

  </table>

  {% endif %}


{% endblock %}

quiz/templates/question.html
{% extends "base.html" %}
{% load i18n%}



{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}

{% block content %}

{% if previous.answers %}

  <p class="muted"><small>{% trans "The previous question" %}:</small></p>
  <p>{{ previous.previous_question }}</p>

  {% if previous.previous_outcome %}
	<div class="alert alert-success">
  {% else %}
	<div class="alert alert-warning">
  {% endif %}
  	  <p><small>
		{% trans "Your answer was" %} </small>
		<strong>
		  {{ previous.previous_outcome|yesno:"correct,incorrect" }}
		</strong>
	  </p>

	</div>

	{% include 'correct_answer.html' %}

	<p><strong>{% trans "Explanation" %}:</strong></p>
	<div class="well " style="background-color: #fcf8e3;">
	  <p>{{ previous.previous_question.explanation }}</p>
	</div>

	<hr>

{% endif %}

<br />

{% if question %}

{% if progress %}
<div style="float: right;">
{% trans "Question" %} {{ progress.0|add:1 }} {% trans "of" %} {{ progress.1 }}
</div>
{% endif %}

<p>
  <small class="muted">{% trans "Question category" %}:</small>
  <strong>{{ question.category }}</strong>
</p>

<p class="lead">{{ question.content }}</p>

{% if question.figure %}
    <img src="{{ question.figure.url }}" alt="{{ question.content }}" />
{% endif %}

<form action="" method="POST">{% csrf_token %}
  <input type=hidden name="question_id" value="{{ question.id }}">

  <ul class="list-group">

	{% for answer in form.answers %}
	  <li class="list-group-item">
	    {{ answer }}
	  </li>
	{% endfor %}

  </ul>
    {% if progress.0|add:1 == progress.1 %}
    <input type="submit" value={% trans "Submit" %} class="btn btn-large btn-block btn-warning" >
    {% else %}
        <input type="submit" value={% trans "Next" %} class="btn btn-large btn-block btn-warning" >
    {% endif %}
</form>

{% endif %}

<hr>


{% endblock %}

quiz/templates/result.html
{% extends "base.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title}} {% endblock %}
{% block description %} {% trans "Exam Results for" %} {{ quiz.title }} {% endblock %}

{% block content %}

  {% if previous.answers %}

  <p class="muted"><small>{% trans "The previous question" %}:</small></p>
  <p>{{ previous.previous_question }}</p>
  <p>Your answer was
	<strong>
	  {{ previous.previous_outcome|yesno:"correct,incorrect" }}
	</strong>
  </p>
  {% include 'correct_answer.html' %}
  <p><strong>{% trans "Explanation" %}:</strong></p>


  <div class="well " style="background-color: #fcf8e3;">
    <p>{{ previous.previous_question.explanation }}</p>
  </div>
  <hr>

  {% endif %}

  {% if max_score %}

  <div>
	<h2>{% trans "Exam results" %}</h2>
	<p>
	  <small class="muted">{% trans "Exam title" %}: </small>
	  <strong>{{ quiz.title }}</strong></p>

	<p class="lead">
	  {% trans "You answered" %} {{ score }} {% trans "questions correctly out of" %} {{ max_score }}, {% trans "giving you" %} {{ percent }}  {% trans "percent correct" %}
    {% if percent > 60 %}<a href="{% url 'job-category' quiz.category %}" class="btn btn-success">Apply For Job</a>{% else %}<button class="btn btn-danger">Try Again</button>{% endif %}
	</p>

	{% if quiz.pass_mark %}
	<hr>
        <p class="lead">{{ sitting.result_message }}</p>
	<hr>

	{% endif %}

	<p>{% trans "Review the questions below and try the exam again in the future"%}.</p>

	{% if user.is_authenticated %}

	  <p>{% trans "The result of this exam will be stored in your progress section so you can review and monitor your progression" %}.</p>

	{% endif %}
  </div>


  {% endif %}


  <hr>

  {% if possible %}

  <p class="lead">
	{% trans "Your session score is" %} {{ session }} {% trans "out of a possible" %} {{ possible }}
  </p>

  <hr>

  {% endif %}

  {% if questions %}

    {% for question in questions %}

      <p class="lead">
		{{ question.content }}
	  </p>

	  {% correct_answer_for_all question %}

      {% if question.user_answer %}
      <p>{% trans "Your answer was" %}: {{ question|answer_choice_to_string:question.user_answer }}</p>
      {% endif %}

	  <p><strong>{% trans "Explanation" %}:</strong></p>
	  <div class="well " style="background-color: #fcf8e3;">
		<p>{{ question.explanation|safe }}</p>
	  </div>

	  <hr>

  {% endfor %}

  {% endif %}



{% endblock %}

quiz/templates/single_complete.html
{% extends "base.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}

{% block content %}


{% if user.is_authenticated %}
  <p>{% trans "You have already sat this exam and only one sitting is permitted" %}.</p>
{% else %}
  <p>{% trans "This exam is only accessible to signed in users" %}.</p>
{% endif %}

{% endblock %}

quiz/templates/view_quiz_category.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Quizzes related to" %} {{ category.category }}{% endblock %}

{% block content %}
<h1>{% trans "Quizzes in the" %} <strong>{{ category.category }} </strong>{% trans "category" %}</h1>

  {% with object_list as quizzes %}
    {% if quizzes %}
        <ul>
        {% for quiz in quizzes %}
            <li>
			  <a href="{% url 'quiz_question' quiz_name=quiz.url %}">
				{{ quiz.title }}
			  </a>
			</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no quizzes" %}</p>
    {% endif %}
  {% endwith %}
{% endblock %}